# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Department Name')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Employee Name')),
                ('personal_phone', models.CharField(max_length=28, verbose_name='Personal Phone')),
                ('personal_mobile', models.CharField(max_length=28, verbose_name='Personal Mobile')),
                ('personal_email', models.EmailField(max_length=254, verbose_name='Personal Email')),
                ('work_phone', models.CharField(max_length=28, verbose_name='Work Phone')),
                ('work_mobile', models.CharField(max_length=28, verbose_name='Work Mobile')),
                ('work_email', models.EmailField(max_length=254, verbose_name='Work Email')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_employee.Employee'),
        ),
    ]
