# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Department Name')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_employee.Employee')),
            ],
        ),
    ]
