# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='personal_phone',
        ),
    ]
