# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee', '0002_remove_employee_personal_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='personal_phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=28, verbose_name='Personal Phone'),
            preserve_default=False,
        ),
    ]
